### PR TITLE
Allow to clone DEV or MASTER branch

### PR DESCRIPTION
**Pull request by zaggash**

### CODE REVIEW

**Comment by sparklyballs** [comment]
the $DEV needs to be double quoted, also i think someone else should handle this one, because personally i think giving dev branch access is just asking for reams of support headaches.

**Comment by zaggash** [comment]
Maybe we can discard any issues if dev enable.
Double quote OK, not sure if really needed, it works without.

**Comment by lonix** [comment]
@zaggash This one is almost very mergable, clean good code, But change the switch mechanism to use the variable like so: $ADVANCED_GIT_BRANCH, and while not set defaults to master.
In addition display a warning (if set to other than master), that we will not support this usecase.

**Comment by zaggash** [comment]
Actually it is default to master.
If $DEV is not set (aka false) branch is master.
If the variable is set whatever the value is, the branch will be dev.

**Comment by zaggash** [comment]
Added a warning message

**Comment by zaggash** [comment]
Lonix: I merge your change
Anyway I don't know why you add 2 variables instead of one ?

**Comment by zaggash** [comment]
Regarding you script, both $ADVANCED_GIT_BRANCH and  $GIT_BRANCH must be fill with the same branch name.
What is the point here ?

Or maybe there is $ sign which needs to be removed : 

[ "$ADVANCED_GIT_BRANCH" ] && $GIT_BRANCH=$ADVANCED_GIT_BRANCH
[ "$ADVANCED_GIT_BRANCH" ] && GIT_BRANCH=$ADVANCED_GIT_BRANCH

**Comment by lonix** [comment]
Good point no need to have two variables, just stick to that single $ADVANCED_GIT_REPO.

**Comment by sparklyballs** [comment]
i've just noticed a cock up of mine on this, from when i was going through and putting in the opt out for updates.
cloning into /opt/plexpy and chowning /config.
should add 
chown abc:abc /config 
to the top of the script and change the two current lines chowning /config to chowning /opt/plexpy

**Comment by lonix** [comment]
ok to test

**Comment by lonix** [comment]
ok to test

**Comment by zaggash** [comment]
I let you merge this guys .

**Comment by ljm42** [comment]
It looks like this request is still open, so I'll add a note here... can you please document this option in the README.md?

edit... oh the corresponding Issue is open, not the pull request.  Let me know if I should add my comment somewhere else or if this is ok.

**Pull request merged**
