### PR TITLE
Add SSL key and cert to allow https from scratch

### PR DESCRIPTION
**Pull request by zaggash**
HTTPS is working from scratch now.
Just need to add enable_https = 1

Set your own cert and key in the config folder if needed off course

### CODE REVIEW

**Comment by sparklyballs** [comment]
i think https should be opt in rather than opt out

**Comment by sparklyballs** [comment]
oops, hit close and comment by mistake.

**Comment by zaggash** [comment]
Actually the cert is created but HTTPS is not enabled by defaut.
It works if the end user edit the defaut config and set HTTPS to 1.
The cert is here like an exemple I would say.

**Comment by lonix** [comment]
If the purpose of this line: [ "$NO_SELF_SIGN_CERT" ] && { echo "NOT creating Self Signed certificate"; exit 0; } Being a Opt out of cert creation, i think it should be Opt-in, rather. That way this behavior is simpler to do yourself via, the userscript.sh.

**Comment by zaggash** [comment]
I think the code is pretty simple.
The cert is generated by default unless the variable is set.

This is only to prevent an issue if the HTTPS is enable in the config without the generation of a cert.

**Comment by sparklyballs** [comment]
take the option variable out altogether, generate a cert whatever , leave the user free to enable/disable https in the config.

probably best solution overall....

**Comment by zaggash** [comment]
I did it to avoid unnecessary files on the config folder :)
That the why on my side

**Comment by sparklyballs** [comment]
my recommendation is to scrap the opt in/out part of the keygen script, generate keys by default.
it's one extra folder in /config that amounts to single figure KB's of space used also.

**Comment by lonix** [comment]
Push the ssl keys to/from /config/ssl

**Comment by zaggash** [comment]
**Just checked the app deeper and there is no need to create a **cert.**
The app handle it by itself.

Only PyOpenssl was needed, then it handle the cert generation if selected on the WebUI settings.

**Comment by sparklyballs** [comment]
pyopenssl is in the base.

**Comment by zaggash** [comment]
WAS :)

**Comment by zaggash** [comment]
I think we can close this PR and the linked issue

**Pull request closed without merging**
