### PR TITLE
Rebasing to alpine 3.12. Rework to python3.

### PR DESCRIPTION
**Pull request by nemchik**
Wait for https://github.com/Tautulli/Tautulli/releases to show a stable release supporting py3. Looks like it should be 2.5.0 or later once that releases as stable.

### CODE REVIEW

**Comment by nemchik** [comment]
I'll force push to get CI to rerun once there's a stable release. I just wanted the branch ready for when they drop their release.

**Comment by nemchik** [comment]
Should be ready now. 2.5.2 stable release.

**Review by thelamer — CHANGES_REQUESTED** [review]
This container is non functional with these changes , I rolled down the dep tree, but I am not able to install plexpy due to distro mismatch.

**Comment by nemchik** [comment]
> This container is non functional with these changes , I rolled down the dep tree, but I am not able to install plexpy due to distro mismatch.

Should be fixed now.

**Review by aptalca — APPROVED** [review]

**Pull request merged**
