### PR TITLE
Update to current maintainer

### PR DESCRIPTION
**Pull request by Starbix**
Incase drzoidberg deletes his account or makes a new repo

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by CHBMB** [comment]
jenkins test this please

**Comment by CHBMB** [comment]
@Starbix Has drzoidberg33 stopped maintaining this or something?  Any links with more info at all?

**Comment by sparklyballs** [comment]
droidberg redirects to jonnywong

**Comment by Starbix** [comment]
From the Plex discord: http://imgur.com/a/83Kan

**Comment by CHBMB** [comment]
Fair enough, good enough for me.  Thanks @Starbix

**Pull request merged**
